plugins {
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

dependencies {
    implementation project(':lib')
    implementation project(':server')
    implementation project(':player:gstreamer')
    implementation project(':player:h264-dump')
    implementation project(':player:vlc')
    implementation project(':player:ffmpeg')

    implementation "net.java.dev.jna:jna:${rootProject.ext.jnaVersion}"
    implementation "net.java.dev.jna:jna-platform:${rootProject.ext.jnaVersion}"
    implementation 'org.springframework.boot:spring-boot-starter'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

bootJar {
    archiveBaseName.set('java-airplay-server')
    manifest {
        attributes('Enable-Native-Access': 'ALL-UNNAMED')
    }
}

bootRun {
    jvmArgs '--enable-native-access=ALL-UNNAMED'
}
