dependencies {
    implementation project(':lib')
    implementation project(':server')

    implementation "net.java.dev.jna:jna:${rootProject.ext.jnaVersion}"
    implementation "net.java.dev.jna:jna-platform:${rootProject.ext.jnaVersion}"
    implementation 'uk.co.caprica:vlcj:4.12.1'
    implementation "com.formdev:flatlaf:${rootProject.ext.flatlafVersion}"
}
