# log
logging.file.name=${user.home}/.java-airplay/java-airplay.log
logging.level.org.springframework.web=INFO
logging.level.javax.jmdns=WARN
logging.level.wtf.nanoka=INFO
logging.level.io.netty=INFO
logging.level.io.netty.handler.logging.LoggingHandler=INFO
logging.level.org.freedesktop.gstreamer=INFO
spring.output.ansi.enabled=ALWAYS
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
# airplay
airplay.serverName=Java AirPlay
airplay.width=1920
airplay.height=1080
airplay.fps=60
airplay.identityFile=${user.home}/.java-airplay/identity.key
airplay.audioJitterPackets=3
airplay.requirePairing=true
airplay.hevc=false
# player (gstreamer, ffmpeg, vlc, h264-dump)
player.implementation=gstreamer
player.tray.enabled=true
player.gstreamer.swing=true
player.gstreamer.videoDecoder=auto
player.gstreamer.gpuAdapter=auto
player.gstreamer.videoQueueDepth=2
player.gstreamer.aggressiveFrameDropping=false
player.gstreamer.renderMode=balanced
